default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  socket: /tmp/mysql.sock

development:
  <<: *default
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  database: rails5_development

# Warning: The database defined as "test" will be erased and
test:
  <<: *default
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  database: rails5_test
  
production:
  <<: *default
  host: <%= ENV["MYSQL_HOST"] %>
  port: <%= ENV["MYSQL_PORT"] %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASS"] %>
  database: <%= ENV["MYSQL_DATABASE"] %>
  
